spring:
  application:
    name: user-service
  autoconfigure:
    exclude:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://167.172.180.49:5432/postgres
    username: postgres
    password: go-arena123
    driverClassName: org.postgresql.Driver

eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 5
    prefer-ip-address: true
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://${EUREKA_USERNAME:user}:${EUREKA_PASSWORD:12345}@localhost:8765/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

server:
  port: 8766
  servlet:
    session:
      cookie:
        http-only: true